package main

import (
	"fmt"
	//"github.com/ChimeraCoder/anaconda"
)

func main() {
	x, y, z := 5, 10, 15
	myQueue := new(Queue)
	fmt.Println("Size before calling Init:", myQueue.GetSize())
	fmt.Println("IsEmpty before calling Init:", myQueue.IsEmpty())
	myQueue = myQueue.Init()
	fmt.Println("After calling Init:", *myQueue)
	fmt.Println("Size after calling Init:", myQueue.GetSize())
	fmt.Println("IsEmpty after calling Init:", myQueue.IsEmpty())
	myQueue.Enqueue(x)
	fmt.Println("After calling Enqueue once:", *myQueue)
	fmt.Println("Head after calling Enqueue once:", myQueue.head)
	fmt.Println("Tail after calling Enqueue once:", myQueue.tail)
	fmt.Println("Size after calling Enqueue once:", myQueue.GetSize())
	fmt.Println("IsEmpty after calling Enqueue once:", myQueue.IsEmpty())
	myQueue.Enqueue(y)
	fmt.Println("After calling Enqueue twice:", *myQueue)
	fmt.Println("Head after calling Enqueue twice:", myQueue.head)
	fmt.Println("Tail after calling Enqueue twice:", myQueue.tail)
	fmt.Println("Size after calling Enqueue twice:", myQueue.GetSize())
	fmt.Println("IsEmpty after calling Enqueue twice:", myQueue.IsEmpty())
	myQueue.Enqueue(z)
	fmt.Println("After calling Enqueue three times:", *myQueue)
	fmt.Println("Head after calling Enqueue three times:", myQueue.head)
	fmt.Println("Tail after calling Enqueue three times:", myQueue.tail)
	fmt.Println("Size after calling Enqueue three times:", myQueue.GetSize())
	fmt.Println("IsEmpty after calling Enqueue three times:", myQueue.IsEmpty())
	fmt.Println("Top after calling Enqueue three times:", myQueue.Top())
	fmt.Println("Dequeueing:", myQueue.Dequeue())
	fmt.Println("Top after calling Dequeue once:", myQueue.Top())
	fmt.Println("Head after calling Dequeue once:", myQueue.head)
	fmt.Println("Tail after calling Dequeue once:", myQueue.tail)
	fmt.Println("Size after calling Dequeue once:", myQueue.GetSize())
	fmt.Println("IsEmpty after calling Dequeue once:", myQueue.IsEmpty())
	fmt.Println("Dequeueing:", myQueue.Dequeue())
	fmt.Println("Top after calling Dequeue twice:", myQueue.Top())
	fmt.Println("Head after calling Dequeue twice:", myQueue.head)
	fmt.Println("Tail after calling Dequeue twice:", myQueue.tail)
	fmt.Println("Size after calling Dequeue twice:", myQueue.GetSize())
	fmt.Println("IsEmpty after calling Dequeue twice:", myQueue.IsEmpty())
	fmt.Println("Dequeueing:", myQueue.Dequeue())
	fmt.Println("Top after calling Dequeue three times:", myQueue.Top())
	fmt.Println("Head after calling Dequeue three times:", myQueue.head)
	fmt.Println("Tail after calling Dequeue three times:", myQueue.tail)
	fmt.Println("Size after calling Dequeue three times:", myQueue.GetSize())
	fmt.Println("IsEmpty after calling Dequeue three times:", myQueue.IsEmpty())
}